// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA6SAgQhdkodAbUOf2sGAwghEhSsZwoPY',
    appId: '1:937593406686:web:361dc4b8b832fb33fcae4f',
    messagingSenderId: '937593406686',
    projectId: 'health-tracker-987af',
    authDomain: 'health-tracker-987af.firebaseapp.com',
    storageBucket: 'health-tracker-987af.firebasestorage.app',
    measurementId: 'G-3CGBP342CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJ4wMNJGW1kh4lcbMj9iW5rtXACNv1A8',
    appId: '1:937593406686:android:476984f0fa4b537dfcae4f',
    messagingSenderId: '937593406686',
    projectId: 'health-tracker-987af',
    storageBucket: 'health-tracker-987af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAVHKDGnG5q2JTgO-SJRd8QXoDiKTZhU8',
    appId: '1:937593406686:ios:d0e84dbc7b9c72dbfcae4f',
    messagingSenderId: '937593406686',
    projectId: 'health-tracker-987af',
    storageBucket: 'health-tracker-987af.firebasestorage.app',
    iosBundleId: 'com.example.healthTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAVHKDGnG5q2JTgO-SJRd8QXoDiKTZhU8',
    appId: '1:937593406686:ios:d0e84dbc7b9c72dbfcae4f',
    messagingSenderId: '937593406686',
    projectId: 'health-tracker-987af',
    storageBucket: 'health-tracker-987af.firebasestorage.app',
    iosBundleId: 'com.example.healthTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA6SAgQhdkodAbUOf2sGAwghEhSsZwoPY',
    appId: '1:937593406686:web:7d67dc7efa397b26fcae4f',
    messagingSenderId: '937593406686',
    projectId: 'health-tracker-987af',
    authDomain: 'health-tracker-987af.firebaseapp.com',
    storageBucket: 'health-tracker-987af.firebasestorage.app',
    measurementId: 'G-066YYQS1ZV',
  );
}
